// Generate the Dockerfile for the pre-built production image. `skein build`/`up` bundle the project's
// TypeScript graphs (+ auth/embed) into a self-contained `.skein/build` artifact of plain JS on the
// host (see ../bundle/bundle-project.ts); this Dockerfile is generated INTO that artifact dir, and the
// image simply installs the artifact's pinned production dependencies and runs `skein start` over the
// compiled output. No vite/tsx, no devDependencies, no runtime TypeScript transform — the image
// carries only what it runs. The artifact ships its own `package.json`, so package-manager detection
// and the user's lockfile are irrelevant here; a single `npm install --omit=dev` is deterministic
// because every dependency is exact-pinned.

/** Node major version → base image tag; falls back to 20 (the examples' pin). */
function baseImage(nodeVersion: string | undefined): string {
  const major = nodeVersion?.trim().match(/^\d+/)?.[0] ?? "20";
  return `node:${major}-slim`;
}

export interface DockerfileOptions {
  /** `node_version` from the config (major version); defaults to 20. */
  nodeVersion?: string;
  /** `dockerfile_lines` from the config, appended verbatim after the base layers. */
  dockerfileLines?: readonly string[];
  /** Port the server binds inside the container. */
  port: number;
}

/**
 * Render a `.dockerignore` for the artifact build context. The artifact is self-contained (bundled
 * JS + a pinned `package.json` + the production `langgraph.json`/`schemas.json`), so this mainly keeps
 * the generated Docker assets and any locally-installed `node_modules` out of the image — deps are
 * (re)installed by the build's install step.
 */
export function generateDockerignore(): string {
  return [
    "# Generated by skein — regenerated by `skein build` / `skein up`.",
    ".git",
    "node_modules",
    ".env",
    ".env.*",
    "Dockerfile",
    "compose.yaml",
    ".dockerignore",
    "npm-debug.log*",
    "",
  ].join("\n");
}

/** Render the Dockerfile text for `skein build` / `skein dockerfile`, run against the build artifact. */
export function generateDockerfile(options: DockerfileOptions): string {
  const { nodeVersion, dockerfileLines = [], port } = options;

  const lines = [
    // The syntax directive must be the first line to be honored — it enables the RUN cache mount.
    `# syntax=docker/dockerfile:1`,
    `# Generated by skein — do not edit by hand (regenerated by \`skein build\` / \`skein up\`).`,
    // The build context must be a skein artifact dir (bundled JS + pinned package.json + schemas.json),
    // which `skein build`/`up` create under `.skein/build`. Building this Dockerfile against a raw
    // project dir will fail — run `skein build` instead of `docker build` by hand.
    `# Build context: a \`.skein/build\` artifact produced by \`skein build\` (not the project root).`,
    `FROM ${baseImage(nodeVersion)}`,
    `WORKDIR /app`,
    ``,
    // Install prod deps first for layer caching: the artifact's pinned package.json changes rarely,
    // so this layer is reused across rebuilds while only the bundle layer below re-runs. The BuildKit
    // cache mount keeps the npm cache out of the committed layer.
    `# Install the artifact's pinned production dependencies (exact versions — deterministic).`,
    `COPY package.json ./`,
    `RUN --mount=type=cache,target=/root/.npm \\`,
    `    npm install --omit=dev --omit=optional --no-audit --no-fund`,
    ``,
    `# Copy the pre-built artifact (bundled JS graphs, production langgraph.json, baked schemas).`,
    `COPY . .`,
    ``,
    `ENV NODE_ENV=production`,
    // The bundle ships sourcemaps; enable them so stack traces map back to the original TypeScript.
    `ENV NODE_OPTIONS=--enable-source-maps`,
    `EXPOSE ${port}`,
    // Liveness probe against skein's `/ok` endpoint, targeting the same port the server binds.
    `HEALTHCHECK --interval=30s --timeout=3s --start-period=20s --retries=3 \\`,
    `    CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||${port})+'/ok').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"`,
    // Run unprivileged. The bundle writes nothing to disk, and /app is world-readable, so no chown.
    `USER node`,
    ...dockerfileLines,
    ``,
    `# Serve the compiled artifact against Postgres + Redis (POSTGRES_URI / REDIS_URI from the env).`,
    `# No --port: the server binds $PORT when the platform injects one (Railway/Fly/Render), else its`,
    `# default. Exec form keeps node as PID 1 so SIGTERM reaches skein's graceful-shutdown handler.`,
    `CMD ["npx", "skein", "start", "--store", "postgres", "--queue", "redis", "--host", "0.0.0.0"]`,
  ];
  return `${lines.join("\n")}\n`;
}
